#!/usr/bin/env bash

exec | tee -a /var/log/named_startup.log
exec 2>&1

CONTAINER_NAME=bind
CONTAINER_IMAGE=galaxy3/bind:latest

function start () {
    docker pull ${CONTAINER_IMAGE}
	sudo -E docker run -d --name ${CONTAINER_NAME} \
		-p 10.55.55.2:53:53/tcp \
		-p 10.55.55.2:53:53/udp \
		${CONTAINER_IMAGE}
}

cd /repos/bind/Docker
make pull

ifconfig eth1:0 10.55.55.2 netmask 255.255.255.0 up

container-rm ${CONTAINER_NAME}
start
container-alive-monitor ${CONTAINER_NAME}
