#!/usr/bin/env bash

exec | tee -a /var/log/named_startup.log
exec 2>&1

make pull

systemctl status docker
systemctl start docker
systemctl status docker

cd /repos/bind/Docker

ifconfig eth1:0 10.55.55.2 netmask 255.255.255.0 up

function remove () {
	docker ps -a | grep bind && (docker stop bind ; docker rm bind)
}

function start () {
    docker pull galaxy3/bind:latest
	sudo -E docker run -d --name bind \
		-p 10.55.55.2:53:53/tcp \
		-p 10.55.55.2:53:53/udp \
		galaxy3/bind:latest
}

function monitor () {
	while :
	do
	  sleep 30
	  docker ps | grep bind || exit 1
	done
}
remove
start
monitor

#make pull
#make rm
#make start